# Generated by Django 6.0.6 on 2026-06-25 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingsession',
            unique_together={('Book', 'User', 'Date')},
        ),
    ]
