# Generated by Django 6.0.5 on 2026-06-27 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_readingsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='Score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
