# Generated by Django 6.0.5 on 2026-06-30 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_approved_alter_readingsession_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='PublicationYear',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='FavoriteGenre',
            new_name='favorite_genre',
        ),
        migrations.RenameField(
            model_name='readingsession',
            old_name='Book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='readingsession',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='readingsession',
            old_name='Score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='readingsession',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ApprovedBy',
        ),
        migrations.AddField(
            model_name='book',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='readingsession',
            unique_together={('book', 'user', 'date')},
        ),
    ]
